---
- name: Sync Other Respositories
  ansible.builtin.git:
    repo: "{{ git_user }}/{{ item }}"
    dest: "/opt/ansible/files/{{ item }}"
    key_file: "/home/ansible/.ssh/{{ ansible_hostname }}"
    accept_newhostkey: yes
    force: yes
  loop:
    - .external-configs
    - external-docker-compose
    - internal-docker-compose
    - .userconfigs
    - RoosterRecorder
    - yt-archive
